import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  view: {
    flex: 1,
    backgroundColor: 'black',
  },
  topBar: {
    backgroundColor: '#000',
    padding: 7,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0.2,
    borderBottomColor: 'rgba(255, 255, 255, 0.2)',
  },
  topBarText: {
    color: 'white',
    fontSize: 15,
    fontWeight: 'bold',
  },
  bookButton: {
    backgroundColor: '#696969',
    paddingVertical: 7,
    paddingHorizontal: 15,
    marginTop: 40,
    marginRight: 1,
    marginLeft: 10,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  chapterButton: {
    backgroundColor: '#696969',
    paddingVertical: 7,
    paddingHorizontal: 15,
    marginTop: 40,
    marginRight: 10,
    marginLeft: 1,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  modal: {
    justifyContent: 'flex-start',
    backgroundColor: 'black',
    margin: 0,
    marginTop: 50,
  },
  modalContent: {
    backgroundColor: '#000',
    borderRadius: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#111',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalClose: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
  modalTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalItem: {
    padding: 20,
  },
  modalItemText: {
    color: 'white',
    fontSize: 17,
  },
  searchInput: {
    height: 40,
    width: '90%',
    backgroundColor: '#222',
    color: 'white',
    paddingHorizontal: 12,
    fontSize: 16,
    borderRadius: 8,
  },
  verseContainer: {
    flex: 1,
    paddingHorizontal: 7,
  },
  verseText: {
    fontFamily: 'times-new-roman',
    color: 'white',
    fontSize: 23,
    marginBottom: 10,
    lineHeight: 30,
  },
  verseNumber: {
    fontWeight: 'bold',
    color: '#ccc',
    fontSize: 13,
  },
  navButtonsContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    marginBottom: 20,
    backgroundColor: 'rgba(255, 255, 255, 0)',
  },
  navButtonPlaceholder: {
    width: 50,
    height: 50,
  },
  navButton: {
    width: 50,
    height: 50,
    backgroundColor: '#696969',
    padding: 10,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButtonText: {
    color: 'white',
    fontSize: 25,
    fontWeight: 'bold',
  },
});
