export const FLATLIST_PERFORMANCE_CONFIG = {
  VERSES: {
    ITEM_HEIGHT: 54,
    MAX_TO_RENDER_PER_BATCH: 10,
    WINDOW_SIZE: 45,
    INITIAL_NUM_TO_RENDER: 12,
    UPDATE_CELLS_BATCHING_PERIOD: 200,
  },
  BOOKS_AND_CHAPTERS: {
    ITEM_HEIGHT: 60,
    MAX_TO_RENDER_PER_BATCH: 10,
    WINDOW_SIZE: 50,
    INITIAL_NUM_TO_RENDER: 10,
  },
} as const;
