export const NAVIGATION_BUTTON_SIZE = 50;
export const NAVIGATION_BOTTOM_PADDING = 25;
export const NAVIGATION_TOTAL_HEIGHT = NAVIGATION_BUTTON_SIZE + NAVIGATION_BOTTOM_PADDING;

export const DOUBLE_TAP_THRESHOLD_MS = 300;
