Transform: AWS::Serverless-2016-10-31
Description: VerseLens Bible API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12

Resources:
  BibleAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.12
      
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref BibleApiGateway
        
        RootPath:
          Type: Api
          Properties:
            Path: / 
            Method: ANY
            RestApiId: !Ref BibleApiGateway

  BibleApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'" 

Outputs:
  BibleApiUrl:
    Value: !Sub "https://${BibleApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: BibleApiUrl